import type { FeedbackEntry } from "@/types/feedback";

// Dataset fisso con punteggi medio-alti (SUS "Eccellente"/"Buono"), usato come
// riferimento visivo stabile per la dashboard feedback (es. screenshot in
// tesi): submittedAt è una data fissa, non "adesso", altrimenti lo screenshot
// cambierebbe pixel a ogni esecuzione. Niente whatWorkedWell/challenges/
// suggestions: la sezione "Commenti liberi" resta vuota (esiste comunque
// nell'app) solo per non allungare inutilmente questo screenshot.
const FEEDBACK_DASHBOARD_FIXTURE: FeedbackEntry[] = [
  {
    id: "1",
    submittedAt: "2026-03-01T09:00:00.000Z",
    name: "Giulia",
    ageGroup: "alunno",
    gameExperience: "digitale",
    autismIdentification: "no",
    appVersion: "2.0.16",
    digitalVsPhysical: 5,
    gameplayClarity: 5,
    graphics: 4,
    enjoyment: 5,
    funLevel: 5,
    sus1: 5,
    sus2: 1,
    sus3: 5,
    sus4: 1,
    sus5: 5,
    sus6: 2,
    sus7: 5,
    sus8: 1,
    sus9: 4,
    sus10: 1,
  },
  {
    id: "2",
    submittedAt: "2026-03-02T09:00:00.000Z",
    name: "Marco",
    ageGroup: "docente",
    gameExperience: "esperto",
    autismIdentification: "si_diagnosi",
    appVersion: "2.0.16",
    digitalVsPhysical: 4,
    gameplayClarity: 5,
    graphics: 5,
    enjoyment: 4,
    funLevel: 5,
    sus1: 5,
    sus2: 1,
    sus3: 4,
    sus4: 1,
    sus5: 5,
    sus6: 1,
    sus7: 4,
    sus8: 2,
    sus9: 5,
    sus10: 1,
  },
  {
    id: "3",
    submittedAt: "2026-03-03T09:00:00.000Z",
    name: "Sofia",
    ageGroup: "alunno",
    gameExperience: "fisico",
    autismIdentification: "no",
    appVersion: "2.0.16",
    digitalVsPhysical: 5,
    gameplayClarity: 4,
    graphics: 5,
    enjoyment: 5,
    funLevel: 4,
    sus1: 4,
    sus2: 1,
    sus3: 5,
    sus4: 1,
    sus5: 5,
    sus6: 1,
    sus7: 5,
    sus8: 2,
    sus9: 4,
    sus10: 1,
  },
  {
    id: "4",
    submittedAt: "2026-03-04T09:00:00.000Z",
    name: "Luca",
    ageGroup: "docente",
    gameExperience: "esperto",
    autismIdentification: "si_non_diagnosticato",
    appVersion: "2.0.16",
    digitalVsPhysical: 4,
    gameplayClarity: 4,
    graphics: 4,
    enjoyment: 5,
    funLevel: 5,
    sus1: 5,
    sus2: 2,
    sus3: 4,
    sus4: 1,
    sus5: 5,
    sus6: 1,
    sus7: 4,
    sus8: 1,
    sus9: 5,
    sus10: 2,
  },
  {
    id: "5",
    submittedAt: "2026-03-05T09:00:00.000Z",
    name: "Alice",
    ageGroup: "alunno",
    gameExperience: "digitale",
    autismIdentification: "preferisco_non_rispondere",
    appVersion: "2.0.16",
    digitalVsPhysical: 5,
    gameplayClarity: 5,
    graphics: 4,
    enjoyment: 5,
    funLevel: 4,
    sus1: 5,
    sus2: 1,
    sus3: 5,
    sus4: 2,
    sus5: 4,
    sus6: 1,
    sus7: 5,
    sus8: 1,
    sus9: 5,
    sus10: 1,
  },
  {
    id: "6",
    submittedAt: "2026-03-06T09:00:00.000Z",
    name: "Davide",
    ageGroup: "none",
    gameExperience: "fisico",
    autismIdentification: "no",
    appVersion: "2.0.16",
    digitalVsPhysical: 4,
    gameplayClarity: 4,
    graphics: 4,
    enjoyment: 4,
    funLevel: 5,
    sus1: 4,
    sus2: 1,
    sus3: 4,
    sus4: 2,
    sus5: 5,
    sus6: 1,
    sus7: 4,
    sus8: 1,
    sus9: 5,
    sus10: 1,
  },
  {
    id: "7",
    submittedAt: "2026-03-07T09:00:00.000Z",
    name: "Francesca",
    ageGroup: "docente",
    gameExperience: "esperto",
    autismIdentification: "preferisco_non_rispondere",
    appVersion: "2.0.15",
    digitalVsPhysical: 5,
    gameplayClarity: 4,
    graphics: 4,
    enjoyment: 4,
    funLevel: 4,
    sus1: 5,
    sus2: 1,
    sus3: 5,
    sus4: 1,
    sus5: 4,
    sus6: 2,
    sus7: 5,
    sus8: 1,
    sus9: 4,
    sus10: 1,
  },
  {
    id: "8",
    submittedAt: "2026-03-08T09:00:00.000Z",
    name: "Matteo",
    ageGroup: "alunno",
    gameExperience: "digitale",
    autismIdentification: "si_diagnosi",
    appVersion: "2.0.15",
    digitalVsPhysical: 5,
    gameplayClarity: 5,
    graphics: 5,
    enjoyment: 4,
    funLevel: 5,
    sus1: 5,
    sus2: 1,
    sus3: 5,
    sus4: 1,
    sus5: 5,
    sus6: 1,
    sus7: 4,
    sus8: 2,
    sus9: 5,
    sus10: 1,
  },
];

export default FEEDBACK_DASHBOARD_FIXTURE;
