name: Test on push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install deps
        run: npm install
      - name: Test
        run: npm run coverage
