name: Node.js CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build, and test
        run: |
          npm install
          npm run coverage
      - name: Code coverage result
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
